import { Solver } from "./classes/solver";

// const solver2 = new Solver({ columns: 9, lines: 7 });
// solver2
//   .setCellValue({ x: 8, y: 6 }, 3)
//   .setCellValue({ x: 7, y: 5 }, 5)
//   .setCellValue({ x: 7, y: 1 }, 3)
//   .setCellValue({ x: 6, y: 6 }, 4)
//   .setCellValue({ x: 6, y: 4 }, 1)
//   .setCellValue({ x: 5, y: 1 }, 5)
//   .setCellValue({ x: 3, y: 5 }, 2)
//   .setCellValue({ x: 3, y: 2 }, 1)
//   .setCellValue({ x: 3, y: 0 }, 3)
//   .setCellValue({ x: 2, y: 1 }, 5)
//   .setCellValue({ x: 1, y: 2 }, 1)
//   .setCellValue({ x: 0, y: 5 }, 2)
//   .addGroupBorders({ x: 8, y: 4 }, ["up"])
//   .addGroupBorders({ x: 8, y: 2 }, ["down"])
//   .addGroupBorders({ x: 7, y: 4 }, ["right", "up"])
//   .addGroupBorders({ x: 7, y: 3 }, ["right"])
//   .addGroupBorders({ x: 7, y: 2 }, ["right", "down"])
//   .addGroupBorders({ x: 6, y: 5 }, ["right", "up"])
//   .addGroupBorders({ x: 6, y: 4 }, ["right", "down"])
//   .addGroupBorders({ x: 6, y: 1 }, ["up"])
//   .addGroupBorders({ x: 6, y: 0 }, ["right", "up"])
//   .addGroupBorders({ x: 5, y: 6 }, ["right"])
//   .addGroupBorders({ x: 5, y: 4 }, ["right", "up"])
//   .addGroupBorders({ x: 5, y: 3 }, ["right"])
//   .addGroupBorders({ x: 5, y: 2 }, ["right"])
//   .addGroupBorders({ x: 5, y: 1 }, ["right", "up"])
//   .addGroupBorders({ x: 5, y: 0 }, ["right"])
//   .addGroupBorders({ x: 4, y: 5 }, ["up", "right"])
//   .addGroupBorders({ x: 4, y: 4 }, ["down", "right"])
//   .addGroupBorders({ x: 4, y: 2 }, ["down"])
//   .addGroupBorders({ x: 3, y: 6 }, ["right"])
//   .addGroupBorders({ x: 3, y: 5 }, ["right", "up", "down"])
//   .addGroupBorders({ x: 3, y: 3 }, ["right"])
//   .addGroupBorders({ x: 3, y: 2 }, ["right", "up"])
//   .addGroupBorders({ x: 3, y: 1 }, ["right", "down"])
//   .addGroupBorders({ x: 2, y: 6 }, ["right"])
//   .addGroupBorders({ x: 2, y: 4 }, ["down", "right"])
//   .addGroupBorders({ x: 2, y: 2 }, ["right", "up", "down"])
//   .addGroupBorders({ x: 2, y: 0 }, ["right"])
//   .addGroupBorders({ x: 1, y: 6 }, ["right"])
//   .addGroupBorders({ x: 1, y: 5 }, ["left", "up"])
//   .addGroupBorders({ x: 1, y: 4 }, ["up", "right"])
//   .addGroupBorders({ x: 1, y: 3 }, ["left", "right"])
//   .addGroupBorders({ x: 1, y: 2 }, ["left"])
//   .addGroupBorders({ x: 1, y: 1 }, ["right", "up", "down"])
//   .addGroupBorders({ x: 1, y: 0 }, ["left"])
//   .addGroupBorders({ x: 0, y: 4 }, ["up", "down"]);

// console.log(solver2.table.print());
// solver2.enableLog().solve();
// console.log(solver2.table.print());

const solver = new Solver({ columns: 10, lines: 10 });
solver
  .setCellValue({ x: 0, y: 0 }, 3)
  .setCellValue({ x: 0, y: 3 }, 1)
  .setCellValue({ x: 0, y: 5 }, 5)
  .setCellValue({ x: 1, y: 5 }, 1)
  .setCellValue({ x: 2, y: 9 }, 2)
  .setCellValue({ x: 3, y: 0 }, 2)
  .setCellValue({ x: 5, y: 9 }, 3)
  .setCellValue({ x: 6, y: 1 }, 1)
  .setCellValue({ x: 6, y: 4 }, 5)
  .setCellValue({ x: 9, y: 3 }, 4)
  .addGroupBorders({ x: 0, y: 0 }, ["right"])
  .addGroupBorders({ x: 0, y: 4 }, ["up", "down"])
  .addGroupBorders({ x: 0, y: 8 }, ["up", "right"])
  .addGroupBorders({ x: 1, y: 1 }, ["right", "up", "down"])
  .addGroupBorders({ x: 1, y: 2 }, ["left", "up"])
  .addGroupBorders({ x: 1, y: 3 }, ["right", "left"])
  .addGroupBorders({ x: 1, y: 5 }, ["right", "up", "left"])
  .addGroupBorders({ x: 1, y: 6 }, ["up", "left"])
  .addGroupBorders({ x: 1, y: 7 }, ["up", "right"])
  .addGroupBorders({ x: 2, y: 1 }, ["up", "right"])
  .addGroupBorders({ x: 2, y: 2 }, ["right"])
  .addGroupBorders({ x: 2, y: 4 }, ["up", "right", "down"])
  .addGroupBorders({ x: 2, y: 7 }, ["up", "right"])
  .addGroupBorders({ x: 2, y: 9 }, ["down", "left"])
  .addGroupBorders({ x: 3, y: 1 }, ["down", "right"])
  .addGroupBorders({ x: 3, y: 3 }, ["down", "right"])
  .addGroupBorders({ x: 3, y: 4 }, ["up", "right"])
  .addGroupBorders({ x: 3, y: 5 }, ["up", "left"])
  .addGroupBorders({ x: 3, y: 6 }, ["up", "right"])
  .addGroupBorders({ x: 3, y: 8 }, ["down", "right", "up"])
  .addGroupBorders({ x: 4, y: 1 }, ["up", "down", "left"])
  .addGroupBorders({ x: 4, y: 4 }, ["down", "right"])
  .addGroupBorders({ x: 4, y: 6 }, ["right", "down"])
  .addGroupBorders({ x: 4, y: 8 }, ["right", "up"])
  .addGroupBorders({ x: 5, y: 0 }, ["right", "left"])
  .addGroupBorders({ x: 5, y: 2 }, ["right", "up", "left"])
  .addGroupBorders({ x: 5, y: 3 }, ["right", "up"])
  .addGroupBorders({ x: 5, y: 5 }, ["right", "down"])
  .addGroupBorders({ x: 5, y: 6 }, ["right", "up"])
  .addGroupBorders({ x: 5, y: 7 }, ["left"])
  .addGroupBorders({ x: 5, y: 8 }, ["right", "up"])
  .addGroupBorders({ x: 6, y: 1 }, ["right", "up", "down"])
  .addGroupBorders({ x: 6, y: 3 }, ["right", "down"])
  .addGroupBorders({ x: 6, y: 5 }, ["right", "up"])
  .addGroupBorders({ x: 6, y: 7 }, ["right", "up", "down"])
  .addGroupBorders({ x: 6, y: 9 }, ["right", "down"])
  .addGroupBorders({ x: 7, y: 1 }, ["right", "down"])
  .addGroupBorders({ x: 7, y: 3 }, ["up", "right"])
  .addGroupBorders({ x: 7, y: 4 }, ["up", "right"])
  .addGroupBorders({ x: 7, y: 7 }, ["right", "down"])
  .addGroupBorders({ x: 8, y: 1 }, ["right", "up"])
  .addGroupBorders({ x: 8, y: 2 }, ["right", "up"])
  .addGroupBorders({ x: 8, y: 5 }, ["left", "down", "up"])
  .addGroupBorders({ x: 8, y: 8 }, ["right", "down", "up"])
  .addGroupBorders({ x: 8, y: 9 }, ["left"])
  .addGroupBorders({ x: 9, y: 1 }, ["down"])
  .addGroupBorders({ x: 9, y: 4 }, ["left", "down"])
  .addGroupBorders({ x: 9, y: 1 }, ["right", "down"])
  .addGroupBorders({ x: 9, y: 6 }, ["left", "up"])
  .addGroupBorders({ x: 9, y: 7 }, ["left"]);

console.log(solver.table.print());
solver.enableLog().solve();
console.log(solver.table.print());
